import type { BitPart } from "./types";

export const BIT_PARTS: Record<string, BitPart> = {
  attack: {
    id: "attack",
    name: "赤紅軸心",
    englishName: "Red Bit",
    maxRpm: 5900,
    rpmDecay: 390,
    speed: 12,
    friction: 0.12,
    massContribution: 0.11,
  },
  defense: {
    id: "defense",
    name: "玄武軸心",
    englishName: "Iron Bit",
    maxRpm: 5000,
    rpmDecay: 270,
    speed: 6,
    friction: 0.05,
    massContribution: 0.18,
  },
  stamina: {
    id: "stamina",
    name: "黃金軸心",
    englishName: "Sol Bit",
    maxRpm: 5500,
    rpmDecay: 290,
    speed: 9,
    friction: 0.02,
    massContribution: 0.08,
  },
  balance: {
    id: "balance",
    name: "翡翠軸心",
    englishName: "Emerald Bit",
    maxRpm: 5300,
    rpmDecay: 310,
    speed: 9.5,
    friction: 0.08,
    massContribution: 0.13,
  },
  crusher: {
    id: "crusher",
    name: "黑曜軸心",
    englishName: "Obsidian Bit",
    maxRpm: 5100,
    rpmDecay: 330,
    speed: 8,
    friction: 0.1,
    massContribution: 0.17,
  },
  phantom: {
    id: "phantom",
    name: "幻影軸心",
    englishName: "Phantom Bit",
    maxRpm: 6000,
    rpmDecay: 400,
    speed: 11.5,
    friction: 0.11,
    massContribution: 0.09,
  },
  aegis: {
    id: "aegis",
    name: "白銀軸心",
    englishName: "Silver Bit",
    maxRpm: 5150,
    rpmDecay: 260,
    speed: 7,
    friction: 0.04,
    massContribution: 0.16,
  },
  vampire: {
    id: "vampire",
    name: "暗夜軸心",
    englishName: "Blood Bit",
    maxRpm: 5400,
    rpmDecay: 300,
    speed: 8.5,
    friction: 0.03,
    massContribution: 0.1,
    spinSteal: 0.5,
  },
  zephyr: {
    id: "zephyr",
    name: "蒼穹軸心",
    englishName: "Azure Bit",
    maxRpm: 5700,
    rpmDecay: 360,
    speed: 12,
    friction: 0.09,
    massContribution: 0.07,
  },
  berserk: {
    id: "berserk",
    name: "狂焰軸心",
    englishName: "Blaze Bit",
    maxRpm: 6000,
    rpmDecay: 330,
    speed: 14.0,
    friction: 0.12,
    massContribution: 0.17,
  },
};
