import type { BladePart } from "./types";

export const BLADE_PARTS: Record<string, BladePart> = {
  attack: {
    id: "attack",
    name: "赤紅戰刃",
    englishName: "Red Blade",
    ai: "seek",
    damageTaken: 0.6,
    counteredBy: "defense",
    color: 0xe60012,
    massContribution: 0.66,
    exclusiveTo: "attack",
  },
  attack_v2: {
    id: "attack_v2",
    name: "赤紅烈風",
    englishName: "Red Tempest",
    ai: "seek",
    damageTaken: 0.55,
    counteredBy: "defense",
    color: 0xff3300,
    massContribution: 0.82,
    exclusiveTo: "attack",
  },
  defense: {
    id: "defense",
    name: "玄武戰刃",
    englishName: "Iron Blade",
    ai: "hold",
    damageTaken: 0.5,
    counteredBy: "vampire",
    color: 0x7a8b99,
    massContribution: 1.08,
    exclusiveTo: "defense",
  },
  stamina: {
    id: "stamina",
    name: "黃金戰刃",
    englishName: "Sol Blade",
    ai: "orbitEvade",
    damageTaken: 1.2,
    counteredBy: "attack",
    color: 0xffc800,
    massContribution: 0.48,
    exclusiveTo: "stamina",
  },
  balance: {
    id: "balance",
    name: "翡翠戰刃",
    englishName: "Emerald Blade",
    ai: "adaptive",
    damageTaken: 0.9,
    counteredBy: "phantom",
    color: 0xb5e61d,
    massContribution: 0.78,
    exclusiveTo: "balance",
  },
  crusher: {
    id: "crusher",
    name: "黑曜戰刃",
    englishName: "Obsidian Blade",
    ai: "seek",
    damageTaken: 0.7,
    counteredBy: "zephyr",
    color: 0xd4883b,
    massContribution: 1.02,
    exclusiveTo: "crusher",
  },
  phantom: {
    id: "phantom",
    name: "幻影戰刃",
    englishName: "Phantom Blade",
    ai: "strafe",
    damageTaken: 0.8,
    counteredBy: "stamina",
    color: 0xa855f7,
    massContribution: 0.54,
    exclusiveTo: "phantom",
  },
  aegis: {
    id: "aegis",
    name: "白銀戰刃",
    englishName: "Silver Blade",
    ai: "counterHold",
    damageTaken: 0.55,
    counteredBy: "berserk",
    color: 0xe2e8f0,
    massContribution: 0.96,
    exclusiveTo: "aegis",
  },
  vampire: {
    id: "vampire",
    name: "暗夜戰刃",
    englishName: "Blood Blade",
    ai: "seek",
    damageTaken: 1.1,
    counteredBy: "crusher",
    color: 0xe11d48,
    massContribution: 0.6,
    exclusiveTo: "vampire",
  },
  zephyr: {
    id: "zephyr",
    name: "蒼穹戰刃",
    englishName: "Azure Blade",
    ai: "strafe",
    damageTaken: 0.85,
    counteredBy: "aegis",
    color: 0x0ea5e9,
    massContribution: 0.42,
    exclusiveTo: "zephyr",
  },
  berserk: {
    id: "berserk",
    name: "狂焰戰刃",
    englishName: "Blaze Blade",
    ai: "seek",
    damageTaken: 0.85,
    counteredBy: "balance",
    color: 0xf97316,
    massContribution: 1.02,
    attackMultiplier: 1.5,
    exclusiveTo: "berserk",
  },
};
